version: 2

jobs:
  test:
    docker:
      - image: cimg/openjdk:15.0.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle test


workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - test
