version: 2.1

workflows:
  pipeline:
    jobs:
      - test

executors:
  openjdk:
    docker:
      - image: cimg/openjdk:21.0

jobs:
  test:
    executor: openjdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew test
      - run: ./gradlew sonarqube -Dsonar.verbose=true
