---
name: Pull request verification

on:
  pull_request:
  workflow_dispatch:

env:
  JAVA_DISTRIBUTION: 'temurin'
  JAVA_VERSION: '17'

# Cancel in-progress PR verification workflows. We only care about verifying the latest commit.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  unit_tests:
    name: unit tests
    runs-on: ubuntu-latest
    container:
      image: fedora:38
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump sonar vars
        run: |
          echo ${{ github.event.pull_request.number }}
          echo ${{ github.base_ref }}
          echo ${{ github.head_ref }}

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        shell: bash
        run: dnf --setopt install_weak_deps=False install -y gettext jss

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Run unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test coverage

      - name: Archive reports
        uses: actions/upload-artifact@v3
        with:
          name: unit_test_reports
          path: |
            **/build/jacoco.xml
#            **/build/jacoco/test.exec
