---
name: Sonar analysis for pull requests

on:
  workflow_run:
    workflows:
      - Pull request verification
    types:
      - in_progress
env:
  JAVA_DISTRIBUTION: 'temurin'
  JAVA_VERSION: '17'

# Cancel in-progress sonar branch analysis workflows. We only care about analyzing the latest commit.
concurrency:
  group: ${{ github.event.workflow.name }}-${{ github.event.workflow_run.pull_requests[0].number }}
  cancel-in-progress: true

jobs:
  pr_sonar_analysis:
    name: PR sonar analysis
    runs-on: ubuntu-latest
    container:
      image: fedora:38
    steps:
      - name: Mask secrets
        shell: bash
        run: |
          echo "::add-mask::${{ secrets.GITHUB_TOKEN }}"
          echo "::add-mask::${{ secrets.SONAR_TOKEN }}"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump sonar vars
        run: |
          echo ${{ github.event.workflow_run.pull_requests[0].number }}
          echo ${{ github.event.workflow_run.pull_requests[0].base.ref }}
          echo ${{ github.event.workflow_run.pull_requests[0].head.ref }}

      - name: Install dependencies
        shell: bash
        run: dnf --setopt install_weak_deps=False install -y gettext jss git tree

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          # checkout commit that triggered this workflow
          ref: ${{ github.event.workflow_run.pull_requests[0].head.ref }}
          # Shallow clones should be disabled for a better relevancy of analysis
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Run tests and coverage
        run: ./gradlew test coverage

      - name: Project tree
        run: tree

      - name: List coverage files
        run: ls -al **/build/reports/jacoco/test

      - name: Print coverage report
        run: cat **/build/reports/jacoco/test/jacocoTestReport.xml

      - name: Run sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar -x test -x coverage --debug
          -Dsonar.log.level=TRACE
          -Dsonar.verbose=true
          -Dsonar.scm.provider=git
          -Dsonar.pullrequest.key=${{ github.event.workflow_run.pull_requests[0].number }}
          -Dsonar.pullrequest.base=${{ github.event.workflow_run.pull_requests[0].base.ref }}
          -Dsonar.pullrequest.branch=${{ github.event.workflow_run.pull_requests[0].head.ref }}
          -Dorg.gradle.jvmargs=-Xmx1g
